#!/bin/bash

# This script generates a system information report.
# It gathers details about the system, hardware, network, and system status.

# This gets the current username and date/time for the report header
USERNAME=$(whoami)  # Get the current user
DATE_TIME=$(date)   # Get the current date and time

# This section displays the system information
HOSTNAME=$(hostname)  # Get the system's hostname
OS=$(cat /etc/os-release | grep "PRETTY_NAME" | cut -d '"' -f 2)  # Get the OS name and version
UPTIME=$(uptime -p)  # Get the system uptime

# This section displays the hardware information
CPU=$(lscpu | grep "Model name" | cut -d ':' -f 2 | xargs)  # Get the CPU model name
RAM=$(free -h | grep Mem | awk '{print $2}')  # Get the total installed RAM
DISKS=$(lsblk -o NAME,SIZE | grep -v "NAME" | awk '{print $1 " " $2}' | tr '\n' ',' | sed 's/,$/\n/')  # Get disk names and sizes
VIDEO=$(lspci | grep -i vga | cut -d ':' -f 3 | xargs)  # Get the video card model

# This section displays the network information
FQDN=$(hostname -f)  # Get the Fully Qualified Domain Name (FQDN)
HOST_ADDRESS=$(hostname -I | awk '{print $1}')  # Get the IP address of the primary network interface
GATEWAY_IP=$(ip route | grep default | awk '{print $3}')  # Get the default gateway IP address
DNS_SERVER=$(grep nameserver /etc/resolv.conf | awk '{print $2}')  # Get the DNS server IP address

# This section displays the system status
USERS_LOGGED_IN=$(who | awk '{print $1}' | sort | uniq | tr '\n' ',' | sed 's/,$/\n/')  # Get a list of logged-in users
DISK_SPACE=$(df -h | grep -v tmpfs | awk '{print $6 " " $4}')  # Get free disk space for each filesystem
PROCESS_COUNT=$(ps -e | wc -l)  # Get the total number of running processes
LOAD_AVERAGES=$(uptime | awk -F 'load average: ' '{print $2}')  # Get the system load averages
LISTENING_PORTS=$(ss -tuln | grep LISTEN | awk '{print $5}' | cut -d ':' -f 2 | sort -n | uniq | tr '\n' ',' | sed 's/,$/\n/')  # Get a list of listening network ports
UFW_STATUS=$(sudo ufw status | grep "Status" | awk '{print $2}')  # Get the status of UFW (firewall)

# This prints the report using EOF for clean formatting
cat <<EOF

System Report generated by $USERNAME, $DATE_TIME

System Information
------------------
Hostname: $HOSTNAME
OS: $OS
Uptime: $UPTIME

Hardware Information
--------------------
cpu: $CPU
Ram: $RAM
Disk(s): $DISKS
Video: $VIDEO

Network Information
-------------------
FQDN: $FQDN
Host Address: $HOST_ADDRESS
Gateway IP: $GATEWAY_IP
DNS Server: $DNS_SERVER

System Status
-------------
Users Logged In: $USERS_LOGGED_IN
Disk Space: $DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVERAGES
Listening Network Ports: $LISTENING_PORTS
UFW Status: $UFW_STATUS

EOF
